### ISSUE TITLE
debug variables aren't set before they are used when trying to run locally

### ISSUE THREAD

**Issue by baynewc1** [enufacas/azureDevOps.CostSavings#1]
debug variables aren't set before they are used when trying to run locally:

![image](https://user-images.githubusercontent.com/7177740/81021408-31957e80-8ebf-11ea-9150-5e54ccfbc98b.png)

For example, env:SYSTEM_TEAMFOUNDATIONCOLLECTIONURI is used on line 2 but set on line 6

This is an issue in both scripts

**Comment by enufacas** [comment]
Good point, yep when running it locally just comment out line 2, and make sure to set the local debug section variables. I will try and clarify this in the script.

**Comment by enufacas** [comment]
I expanded the comments a bit more to clarify what should be commented out with local debugging. Thanks for calling this out
https://github.com/enufacas/azureDevOps.CostSavings/blob/907c03ea704d6c43612ff6202d4b94c9fb3ac30d/cost-savings-pipelines.ps1#L2
