### ISSUE TITLE
User variable not defined

### ISSUE THREAD

**Issue by baynewc1** [enufacas/azureDevOps.CostSavings#3]
This variable is not defined anywhere in the script. Is it expected to be an environment variable? if so, it should be a part of the local debug section:

![image](https://user-images.githubusercontent.com/7177740/81021727-efb90800-8ebf-11ea-8b7e-6d3610134ede.png)

**Comment by enufacas** [comment]
Hey Warwick yeah that is just an empty variable, it is not set locally or with an environment variable. There is actually a[ better way ](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/powershell?view=azure-devops#use-the-oauth-token-to-access-the-rest-api)to create this auth flow, I will update it when I have a chance. 

But anyway it should not be a problem, As long as you have the PAT\System Access token defined it will authenticate, user being empty shouldn't matter.

**Comment by enufacas** [comment]
@baynewc1 I made this better using a newer style auth model. Easier to understand now. 
https://github.com/enufacas/azureDevOps.CostSavings/blob/907c03ea704d6c43612ff6202d4b94c9fb3ac30d/cost-savings-license.ps1#L18
